[app]
name = "Actix Web"
key = ""
url = "http://127.0.0.1:8080"

[server]
addrs = "127.0.0.1:8080"

[database]
url = "mysql://root:123456@127.0.0.1:3306/rust_web"

[redis]
url = "redis://127.0.0.1:6379"

