[app]
name = "Actix Web"
key = "your-secret-key" # Should be a strong random key
url = "http://127.0.0.1:8081"
debug = false

[app.metadata]
title = "Actix Web Application"
keywords = "rust, actix, web, api"
description = "A powerful web application built with Actix Web framework"

[server]
addrs = "127.0.0.1:8081"

[redis]
url = "redis://127.0.0.1:6379"

[cookie]
name = "SESSIONID"
secret_key = "dpp7QFH3QR41Ims6mIjdTysAtkM9bOoN3gJAaF0X5HqbKdGdVhWQcdMcJTtqjpUAL4EolObWxhG9s8uN2e32vA=="

[post_client]
addrs = ["http://127.0.0.1:8080"]

[auth_client]
addrs = ["http://127.0.0.1:8080"]
